[workspace]
resolver = "2"
members = [
  "crates/codegen",
  "crates/platform",
  "crates/util",
  "crates/w3gs",
  "crates/w3map",
  "crates/w3c",
  "crates/blp",
  "crates/lan",
  "crates/log",
  "crates/log-subscriber",
  "crates/config",
  "crates/net",
  "crates/w3storage",
  "crates/w3replay",
  "crates/constants",
  "crates/event",
  "crates/task",
  "crates/types",
  "crates/debug",
  "crates/observer",
  "crates/observer-fs",
  "crates/observer-archiver",
  "crates/kinesis",
  "crates/replay",

  "crates/controller",
  "crates/node",
  "crates/client",
  "crates/observer-edge",

  "binaries/flo",
  "binaries/flo-cli",
  "binaries/flo-controller-service",
  "binaries/flo-node-service",
  "binaries/flo-worker",
  "binaries/flo-worker-ui",
  "binaries/flo-ping",
  "binaries/flo-stats-service",

  "deps/flo-grpc"
]

[patch.crates-io]
#stormlib = { path = "../stormlib-rs/crates/stormlib" }
#stormlib-sys = { path = "../stormlib-rs/crates/stormlib-sys" }
stormlib = { git = "https://github.com/wc3tools/stormlib-rs.git" }
stormlib-sys = { git = "https://github.com/wc3tools/stormlib-rs.git" }
casclib = { git = "https://github.com/wc3tools/casclib-rs.git" }
casclib-sys = { git = "https://github.com/wc3tools/casclib-rs.git" }
#s2-grpc-utils = { path = "../s2-grpc-utils" }
s2-grpc-utils = { git = "https://github.com/Ventmere/s2-grpc-utils.git", branch = "0.2" }
#flo-state = { path = "../flo-state" }
bs-diesel-utils = { git = "https://github.com/BSpaceinc/bs-diesel-utils.git" }
async-dnssd = { git = "https://github.com/stbuehler/rust-async-dnssd.git" }

[profile.release-with-debug]
inherits = "release"
debug = true

[workspace.metadata.crane]
name = "flo"

[workspace.package]
version = "0.18.0"
edition = "2021"
license = "MIT"
